import React, { useMemo, useState } from 'react';
import { ArrowLeft, MapPin, Phone, Navigation, Search, ShieldCheck, Clock } from '../../shared/icons';
import { distanceKm, formatKm } from '../../data/mockData';

const TYPES=['All','Hospital','Clinic','24x7 Pharmacy','Ambulance','Petrol Pump','Garage','Tyre / Puncture','Battery / Jump Start','Mechanic','Blood Bank','Diagnostic / Lab'];

function EmergencyCard({ item, distance, onVerifyRequest }) {
  const maps=()=>window.open(`https://maps.google.com/?q=${item.lat},${item.lng}`,'_blank');
  return <div className="bg-white rounded-2xl p-4 border border-gray-100 mb-3"><div className="flex justify-between gap-3"><div><div className="font-bold text-sm">{item.name}</div><div className="text-xs text-gray-400 mt-0.5">{item.type} · {item.area || item.city || ''}</div></div>{item.verified&&<span className="text-[9px] bg-emerald-100 text-emerald-700 px-2 py-1 rounded-full font-bold h-fit"><ShieldCheck size={10} className="inline"/> VERIFIED</span>}</div><div className="text-xs text-gray-500 mt-2">{item.address}</div><div className="flex items-center gap-2 mt-2 text-[11px] text-violet-600 font-semibold"><MapPin size={11}/>{formatKm(distance)} {item.open24 ? '· Open 24×7' : item.openNow ? '· Open now' : ''}</div><div className="flex gap-2 mt-3"><a href={`tel:${item.phone}`} className="flex-1 text-center bg-emerald-50 text-emerald-700 rounded-lg py-2 text-xs font-bold"><Phone size={12} className="inline"/> Call</a><button onClick={maps} className="flex-1 bg-blue-50 text-blue-700 rounded-lg py-2 text-xs font-bold"><Navigation size={12} className="inline"/> Directions</button></div></div>;
}

export default function Emergency({ services=[], userCoords, onBack, onSuggest }) {
  const [type,setType]=useState('All');
  const [query,setQuery]=useState('');
  const q=query.trim().toLowerCase();
  const list=useMemo(()=>services.filter(s=>s.status==='verified'&&s.verified&& (type==='All'||s.type===type) && (!q||s.name.toLowerCase().includes(q)||s.address.toLowerCase().includes(q)||s.area?.toLowerCase().includes(q))).map(s=>({...s,d:distanceKm(userCoords?.lat,userCoords?.lng,s.lat,s.lng)})).sort((a,b)=>(a.d??999)-(b.d??999)),[services,userCoords,type,q]);
  return <div className="pb-24 min-h-screen bg-gray-50"><div className="bg-gradient-to-br from-red-500 to-rose-600 px-5 pt-6 pb-6 rounded-b-3xl text-white"><button onClick={onBack} className="mb-3"><ArrowLeft size={20}/></button><div className="text-2xl font-extrabold">🚨 Emergency</div><div className="text-white/85 text-sm mt-1">Verified nearby emergency services — zarurat ke waqt fast access.</div><div className="mt-3 bg-white rounded-xl flex items-center px-3 py-2"><Search size={16} className="text-gray-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hospital, garage, petrol pump..." className="flex-1 outline-none px-2 text-sm text-gray-700"/></div></div><div className="px-5 mt-4 flex gap-2 overflow-x-auto pb-1">{TYPES.map(t=><button key={t} onClick={()=>setType(t)} className={`px-3 py-2 rounded-full text-[11px] font-semibold whitespace-nowrap ${type===t?'bg-red-500 text-white':'bg-white text-gray-500 border border-gray-200'}`}>{t}</button>)}</div><div className="px-5 mt-4">{list.length?list.map(s=><EmergencyCard key={s.id} item={s} distance={s.d}/>):<div className="bg-white rounded-2xl p-5 text-center text-sm text-gray-500">Is category me verified service nahi mili. Aap missing place suggest kar sakte hain.</div>}<button onClick={onSuggest} className="w-full bg-white border-2 border-dashed border-red-200 text-red-600 font-bold py-3 rounded-xl mt-3">➕ Missing Emergency Place Suggest Karein</button><div className="bg-amber-50 border border-amber-100 rounded-xl p-3 mt-3 text-[10px] text-amber-700"><b>Safety:</b> Public suggestion turant live nahi hoti. Pehle verification hoti hai; sirf verified listings emergency search me dikhengi.</div></div></div>;
}

export function EmergencySuggest({ onClose, onSubmit }) {
  const [form,setForm]=useState({type:'Garage',name:'',address:'',area:'',phone:''});
  return <div className="fixed inset-0 z-50 bg-black/50 flex items-end"><div className="w-full max-w-md mx-auto bg-white rounded-t-3xl p-5 max-h-[90vh] overflow-y-auto"><div className="flex justify-between items-center mb-3"><div><div className="font-bold">Missing Emergency Place</div><div className="text-xs text-gray-400">Aap suggest kar sakte hain; live hone se pehle verification zaruri hai.</div></div><button onClick={onClose}>✕</button></div><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="w-full border rounded-xl px-3 py-3 text-sm mb-2">{TYPES.slice(1).map(t=><option key={t}>{t}</option>)}</select><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Place / shop / hospital ka naam" className="w-full border rounded-xl px-3 py-3 text-sm mb-2"/><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Poora address / landmark" rows={2} className="w-full border rounded-xl px-3 py-3 text-sm mb-2"/><input value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="Area / Mohalla" className="w-full border rounded-xl px-3 py-3 text-sm mb-2"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value.replace(/\D/g,'').slice(0,10)})} placeholder="Phone (optional)" className="w-full border rounded-xl px-3 py-3 text-sm mb-3"/><button onClick={()=>{if(!form.name.trim()||!form.address.trim())return alert('Naam aur address required hai.');onSubmit(form);}} className="w-full bg-red-500 text-white font-bold py-3 rounded-xl">Submit for Verification</button></div></div>;
}
