import React, { useState } from 'react';
import { Check, X, MapPin, Phone, ShieldCheck } from '../../shared/icons';

export default function EmergencyAdmin({ services=[], onVerify, onReject, onAdd }) {
  const pending=services.filter(s=>s.status==='pending');
  const live=services.filter(s=>s.status==='verified'&&s.verified);
  const [form,setForm]=useState({type:'Garage',name:'',address:'',area:'',city:'Surat',phone:'',lat:'',lng:'',open24:false,source:'authorized'});
  return <div className="px-5 mt-4 space-y-4">
    <div className="bg-red-50 border border-red-100 rounded-2xl p-4"><div className="font-extrabold text-sm text-red-700">🚨 Emergency Verification</div><div className="text-xs text-red-500 mt-1">Public suggestion turant live nahi hoti. Sirf verified entries customer ko dikhengi.</div></div>
    <div className="bg-white rounded-2xl p-4 border"><div className="font-bold text-sm mb-2">➕ Authorized / Field Verified Place Add</div><div className="text-[10px] text-gray-400 mb-2">Google/field verification se mili real information yahan directly live kar sakte hain.</div><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="w-full border rounded-lg px-2 py-2 text-xs mb-2">{['Hospital','Clinic','24x7 Pharmacy','Ambulance','Petrol Pump','Garage','Tyre / Puncture','Battery / Jump Start','Mechanic','Blood Bank','Diagnostic / Lab'].map(x=><option key={x}>{x}</option>)}</select><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name" className="w-full border rounded-lg px-2 py-2 text-xs mb-2"/><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Address" rows={2} className="w-full border rounded-lg px-2 py-2 text-xs mb-2"/><div className="grid grid-cols-2 gap-2"><input value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="Area" className="border rounded-lg px-2 py-2 text-xs"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone" className="border rounded-lg px-2 py-2 text-xs"/></div><div className="grid grid-cols-2 gap-2 mt-2"><input value={form.lat} onChange={e=>setForm({...form,lat:e.target.value})} placeholder="Latitude" className="border rounded-lg px-2 py-2 text-xs"/><input value={form.lng} onChange={e=>setForm({...form,lng:e.target.value})} placeholder="Longitude" className="border rounded-lg px-2 py-2 text-xs"/></div><select value={form.source} onChange={e=>setForm({...form,source:e.target.value})} className="w-full border rounded-lg px-2 py-2 text-xs mt-2"><option value="authorized">Field / Authorized verification</option><option value="google">Google / public source then verified</option></select><label className="flex items-center gap-2 text-xs mt-2"><input type="checkbox" checked={form.open24} onChange={e=>setForm({...form,open24:e.target.checked})}/> Open 24×7</label><button onClick={()=>{if(!form.name.trim()||!form.address.trim())return alert('Name aur address required.');onAdd(form);setForm({...form,name:'',address:'',area:'',phone:'',lat:'',lng:'',open24:false})}} className="w-full mt-3 bg-red-500 text-white py-2.5 rounded-lg text-xs font-bold">Add Verified & Live</button></div>
    <div className="bg-white rounded-2xl p-4 border"><div className="font-bold text-sm mb-3">Pending ({pending.length})</div>{pending.length===0?<div className="text-xs text-gray-400">No pending suggestions.</div>:pending.map(s=><div key={s.id} className="border-b last:border-0 py-3"><div className="flex justify-between"><div><div className="font-bold text-sm">{s.name}</div><div className="text-xs text-gray-400">{s.type} · {s.area||s.city}</div></div><span className="text-[9px] bg-amber-100 text-amber-700 px-2 py-1 rounded-full font-bold">PENDING</span></div><div className="text-xs text-gray-600 mt-2">{s.address}</div>{s.phone&&<div className="text-xs text-gray-500 mt-1"><Phone size={11} className="inline"/> {s.phone}</div>}<div className="flex gap-2 mt-3"><button onClick={()=>onVerify(s)} className="flex-1 bg-emerald-600 text-white rounded-lg py-2 text-xs font-bold"><Check size={12} className="inline"/> Verify & Live</button><button onClick={()=>onReject(s)} className="flex-1 bg-red-50 text-red-600 rounded-lg py-2 text-xs font-bold"><X size={12} className="inline"/> Reject</button></div></div>)}</div>
    <div className="bg-white rounded-2xl p-4 border"><div className="font-bold text-sm mb-3">Verified Live ({live.length})</div>{live.slice(0,50).map(s=><div key={s.id} className="flex justify-between py-2 border-b last:border-0 text-xs"><span><ShieldCheck size={12} className="inline text-emerald-600"/> {s.name} · {s.type}</span><span className="text-gray-400">{s.city}</span></div>)}</div>
  </div>;
}
