import React, { useMemo } from 'react';
import { Flame, Clock, MapPin } from '../../shared/icons';
import DailyReward from '../rewards/DailyReward';
import PriceAlertPanel from '../alerts/PriceAlertPanel';
import { distanceKm, formatINR } from '../../data/mockData';
import { isPromotionActive } from '../promotions/promotionService';
export default function TodayHub({shops,user,userCoords,onClaimReward,onOpenShop}){
 const deals=useMemo(()=>shops.filter(s=>!s.isBlocked).flatMap(s=>{const out=[];if(s.flashDeal&&new Date(s.flashDeal.expiresAt).getTime()>Date.now())out.push({kind:'flash',shop:s,title:s.flashDeal.productName||s.flashDeal.item,old:s.flashDeal.originalPrice,new:s.flashDeal.newPrice,expires:s.flashDeal.expiresAt});s.products.forEach(p=>{if(isPromotionActive(p.promotion)&&(p.promotion.type==='discount'||p.promotion.type==='flash'))out.push({kind:p.promotion.type,shop:s,title:p.name,old:p.price,new:p.promotion.newPrice||p.price,discount:p.promotion.discount,expires:p.promotion.expiresAt})});return out}).slice(0,10),[shops]);
 return <div className="pb-24"><div className="bg-gradient-to-br from-orange-400 to-pink-500 px-5 pt-6 pb-6 rounded-b-3xl text-white"><div className="text-2xl font-extrabold flex items-center gap-2"><Flame size={22}/> Aaj Ka NearShop</div><div className="text-white/80 text-sm mt-1">Nearby deals, rewards aur price alerts — ek jagah.</div></div><div className="px-5 mt-4 space-y-3"><div className="bg-white rounded-2xl p-4 border"><div className="font-extrabold text-sm mb-2">🏷️ Aaj ke nearby deals</div>{deals.length?deals.map((d,i)=><div key={i} onClick={()=>onOpenShop(d.shop)} className="border-b last:border-0 py-3 cursor-pointer"><div className="flex justify-between"><div><div className="text-sm font-bold">{d.title}</div><div className="text-xs text-gray-400 flex items-center gap-1"><MapPin size={10}/>{d.shop.name} · {d.shop.area}</div></div><span className="text-[10px] bg-orange-100 text-orange-600 px-2 py-1 rounded-full font-bold">{d.discount?`${d.discount}% OFF`:'FLASH'}</span></div>{d.old!=null&&<div className="mt-1 text-xs"><span className="line-through text-gray-400 mr-2">{formatINR(Number(d.old))}</span><b className="text-emerald-600">{formatINR(Number(d.new))}</b></div>}<div className="text-[10px] text-gray-400 mt-1 flex items-center gap-1"><Clock size={10}/>{Math.max(0,Math.ceil((new Date(d.expires).getTime()-Date.now())/3600000))}h remaining</div></div>):<div className="text-xs text-gray-400">Aaj abhi deal nahi. Shop owners yahan offers launch kar sakte hain.</div>}</div><div className="bg-white rounded-2xl p-4 border"><div className="font-extrabold text-sm mb-2">📢 Nearby highlights</div>{shops.filter(s=>s.promotion&&isPromotionActive(s.promotion)).slice(0,6).map(s=><div key={s.id} onClick={()=>onOpenShop(s)} className="py-2 border-b last:border-0 cursor-pointer"><div className="flex justify-between"><b className="text-xs">{s.name}</b><span className="text-[9px] bg-violet-100 text-violet-700 px-2 py-0.5 rounded-full font-bold">{s.promotion.badge||'PROMOTED'}</span></div><div className="text-[11px] text-gray-500 mt-1">{s.promotion.message||s.promotion.coupon||'Aaj nearby customers ke liye special visibility active hai.'}</div></div>)}{!shops.some(s=>s.promotion&&isPromotionActive(s.promotion))&&<div className="text-xs text-gray-400">Abhi koi promoted shop highlight nahi.</div>}</div><DailyReward user={user} onClaim={onClaimReward}/><PriceAlertPanel user={user} shops={shops}/><div className="bg-violet-50 rounded-2xl p-4 text-xs text-violet-700"><b>🎯 Need It</b> — item nahi mil raha? Need It free hai; selected category ke nearby shops se availability mangwao.</div></div></div>;
}
