import React, { useEffect, useState } from 'react';
import { supabase } from '../../supabaseClient';
import { Bell, TrendingUp } from '../../shared/icons';
export default function PriceAlertPanel({ user, shops }) {
  const [name,setName]=useState(''); const [target,setTarget]=useState(''); const [alerts,setAlerts]=useState([]); const [hit,setHit]=useState([]);
  const load=async()=>{ const {data}=await supabase.from('price_alerts').select('*').eq('user_id',user.id).eq('active',true).order('created_at',{ascending:false}); const rows=data||[]; setAlerts(rows); setHit(rows.map(a=>({...a,matches:shops.flatMap(s=>s.products.map(p=>({...p,shop:s}))).filter(x=>x.name.toLowerCase().includes(String(a.product_name).toLowerCase())&&Number(x.price)<=Number(a.target_price))})).filter(a=>a.matches.length)); };
  useEffect(()=>{load()},[user.id,shops]);
  const add=async()=>{if(!name.trim()||!(Number(target)>0))return alert('Product aur target price dijiye.');const {data,error}=await supabase.from('price_alerts').insert({user_id:user.id,product_name:name.trim(),target_price:Number(target)}).select().single();if(error)return alert('Price alert save nahi hua: '+error.message);setAlerts(x=>[data,...x]);setName('');setTarget('');};
  return <div className="bg-white rounded-2xl p-4 border"><div className="flex items-center gap-2 font-extrabold text-sm"><Bell size={16} className="text-violet-600"/> Price Alert</div><div className="text-[11px] text-gray-400 mt-1">Price target se neeche aaye to app kholte hi alert dikhega.</div><div className="flex gap-2 mt-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Product name" className="flex-1 border rounded-xl px-3 py-2 text-sm"/><input value={target} onChange={e=>setTarget(e.target.value.replace(/[^0-9.]/g,''))} placeholder="₹ target" className="w-24 border rounded-xl px-3 py-2 text-sm"/><button onClick={add} className="bg-violet-600 text-white px-3 rounded-xl font-bold">+</button></div>{hit.length>0&&<div className="mt-3 bg-emerald-50 rounded-xl p-3"><div className="font-bold text-xs text-emerald-700">🔔 Price Alert Hit!</div>{hit.flatMap(a=>a.matches.slice(0,3).map(x=><div key={a.id+x.shop.id} className="text-xs mt-1">{x.name} — <b>₹{x.price}</b> at {x.shop.name}</div>))}</div>}{alerts.length>0&&<div className="mt-3 space-y-1">{alerts.slice(0,4).map(a=><div key={a.id} className="text-[11px] flex justify-between text-gray-500"><span>{a.product_name}</span><span>≤ ₹{a.target_price}</span></div>)}</div>}<div className="text-[10px] text-gray-400 mt-2 flex items-center gap-1"><TrendingUp size={11}/> Price data current shop listings se compare hota hai.</div></div>;
}
